[package]
name = "extrahop"
version = "0.2.1"
authors = ["Ted Driggs <ted.driggs@outlook.com>"]
repository = "https://github.com/TedDriggs/extrahop"
documentation = "https://docs.rs/extrahop/0.2.1"
license = "MIT"
description = "Client library for the ExtraHop platform."
keywords = ["extrahop"]
readme = "README.md"
categories = ["api-bindings"]

[dependencies]
reqwest = "0.5"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"

[dependencies.error-chain]
version = "0.10"
default-features = false