[package]
name = "extrahop"
version = "0.1.2"
authors = ["Ted Driggs <ted.driggs@outlook.com>"]
repository = "https://github.com/TedDriggs/extrahop"
documentation = "https://docs.rs/extrahop/0.1.2"
license = "MIT"
description = "Client library for the ExtraHop platform."
keywords = ["extrahop"]
readme = "README.md"
categories = ["api-bindings"]

[dependencies]
reqwest = "0.4"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"